replicaCount: 1

image:
  repository: ghcr.io/deeprobin/radioactivity-api:latest

service:
  port: 80
  targetPort: 8080

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85