apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radioactivity-api.fullname" . }}
  labels:
    {{- include "radioactivity-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "radioactivity-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "radioactivity-api.fullname" . }}
    spec:
      replicas: {{ .Values.replicaCount }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
