apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ include "radioactivity-api.fullname" . }}
  name: {{ include "radioactivity-api.fullname" . }}-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "radioactivity-api.fullname" . }}
  type: LoadBalancer
status:
  loadBalancer: {}