name: .NET

on:
  push:
    branches: [ "main" ]
    paths: ["api/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["api/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore RadioactivityApp.sln
    - name: Build
      run: dotnet build RadioactivityApp.sln --no-restore
    - name: Test
      run: dotnet test RadioactivityApp.sln --no-build --verbosity normal