name: Deploy to Kubernetes
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://167.86.76.26:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Helm Chart
        run: helm upgrade --install radioactivity-api ./k8s/charts/radioactivity-api